import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  subsets: ["latin"], // Specify the font subsets you need
  weight: ["400", "700"], // Optional: Specify font weights
  variable: "--font-inter", // Optional: CSS variable for custom styles
});

export const metadata: Metadata = {
  title: "Tailwind UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
